sudo: required
services:
  - docker
before_install:
  - docker build -t nitesh/complex -f ./client/Dockerfile.dev ./client
script:
  - echo "pushing image to docker hub"
after_success:
  - docker build -t nitesh/multi-client ./client
  - docker build -t nitesh/multi-nginx ./nginx
  - docker build -t nitesh/multi-server ./server
  - docker build -t nitesh/multi-worker ./worker

  # login to docker
  - echo "$DockerPassword" | docker login -u "$DockerUser" --password-stdin
  - docker push nitesh/multi-client
  - docker push nitesh/multi-nginx
  - docker push nitesh/multi-server
  - docker push nitesh/multi-worker